[serviceweaver]
binary = "new_it"

["new_it/app/configApp/ConfigApp"]
DbType = "mysql"
Mysql.Ip = "192.168.0.169"
Mysql.Port = "33069"
Mysql.Config= "charset=utf8mb4&parseTime=True&loc=Local"
Mysql.Dbname= "new_it"
Mysql.Username="root"
Mysql.Password="PXDN93VRKUm8TeE7"
Mysql.MaxIdleConns=3
Mysql.MaxOpenConns=10
Mysql.LogMode=""
#jwt config
JWT.ExpiresTime=86400
JWT.BufferTime=604800
JWT.Issuer="new-it"
JWT.SigningKey="ff76be17-bca3-a2f4-a6c3-66da4f1bcfee"